services:
  app:
    build:
      context: ./services/app
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      UV_CACHE_DIR: null
      FLASK_RUN_HOST: null
    networks:
      v0:
        ipv4_address: ${FOMS_IP}
    ports: []
    depends_on:
      postgres:
        condition: service_healthy
    init: true
    command: >
      bash -c "
      ./init.sh &&
      exec uv run gunicorn --bind 0.0.0.0:5000 --workers 3 --chdir src 'server:app'
      "

  nginx:
    image: nginx
    restart: unless-stopped
    volumes:
      - ./services/nginx/conf/flask-app.conf:/etc/nginx/conf.d/default.conf:ro
      - certbot-www:/var/www/certbot
      - certbot-certs:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    networks:
      - v0
    depends_on:
      - app

  certbot:
    image: certbot/certbot
    volumes:
      - certbot-www:/var/www/certbot
      - certbot-certs:/etc/letsencrypt
    command: "certonly --webroot -w /var/www/certbot -d ${DOMAIN} --email ${CERTBOT_EMAIL} --agree-tos --no-eff-email"
    networks:
      - v0

volumes:
  certbot-www:
  certbot-certs:
